### ISSUE TITLE
Files 

### ISSUE THREAD

**Issue by mohamedkaissi** [sachin0raon/Mirror2Gdrive#28]
The files should be deleted after the upload is successfully uploaded to gdrive or telegram, to free up storage,

**Comment by sachinOraon** [comment]
Hi Bro, could you please set `AUTO_DEL_TASK = True` and let me know in case of any issue.

**Comment by mohamedkaissi** [comment]
Sorry bro , it's my bad , I've forgotten to update the config url after I've changed the value to true earlier.

**Comment by mohamedkaissi** [comment]
And about something else , it would be good if there's an update interval, so that the status update by it's own in like 10s or 20s , and uploading status also should be added, if you can Bri

**Comment by mohamedkaissi** [comment]
> Hi Bro, could you please set `AUTO_DEL_TASK = True` and let me know in case of any issue.

Files get deleted after it finish , but folders don't

**Comment by sachinOraon** [comment]
Can you please check out the [dev](https://github.com/sachin0raon/Mirror2Gdrive/tree/dev) branch, folders are getting deleted during my testing.

**Comment by mohamedkaissi** [comment]
I've just tried the dev branch ,still same problem When I sent a zip link to extract it and upload it to gdrive , the zip file got deleted , and the folder stayed.
here's the link of the instance : http://d2e6-2001-41d0-700-6790-00-3f7.in.ngrok.io/

**Comment by mohamedkaissi** [comment]
you can add a cmd like the one on MLTB , /clearlocals to delete anything got downloaded didn't deleted

**Comment by sachin0raon** [comment]
This is now fixed, please check it out.

**Comment by mohamedkaissi** [comment]
in dev or master branch ?

**Comment by sachinOraon** [comment]
in dev branch

**Comment by sachinOraon** [comment]
need to rebuild docker image and retry

**Comment by mohamedkaissi** [comment]
same error

**Comment by mohamedkaissi** [comment]
Now is working great , files and folders get deleted, thanks. 
But something happened I guess a glitch or something like that.
![IMG_20230224_133704](https://user-images.githubusercontent.com/62901183/221180751-ec390c03-4742-4eec-823d-de9b81efebf2.jpg)

**Comment by sachinOraon** [comment]
This minor glitch is now fixed.
