### ISSUE TITLE
Features and Error

### ISSUE THREAD

**Issue by rinrinx** [sachin0raon/Mirror2Gdrive#3]
Reply file  and link  upload .torrent file /aria and /qbit

main - ERROR - Failed to answer callback for: qbit-file#2f18e72afa7d3b9fa1440239fdc78d05825ec29a

if the file is wrong, it is not canceled, can you solve this too?

**Comment by rinrinx2** [comment]
Reply file and link upload .torrent file /aria and /qbit please add this sir

**Comment by rinrinx** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/91373907/218307728-7e4dd627-3a5b-499b-be5f-97e49d2875e9.png)
Reply file and link upload .torrent file /aria and /qbit please add this sir

**Comment by sachin0raon** [comment]
I will add this feature as well.

**Comment by rinrinx** [comment]
Thank you so much

**Comment by rinrinx** [comment]
bro will leech command be added for aria and qbit

**Comment by sachin0raon** [comment]
Hi bro, unfortunately I'm not aware of "leech" functionality, could you please briefly explain what does it mean.

**Comment by rinrinx** [comment]
/arialeech command will download the link and upload it to telegram
/qbitleech command will download torrent and upload to telegram

**Comment by sachin0raon** [comment]
> ![Screenshot_3](https://user-images.githubusercontent.com/91373907/218307728-7e4dd627-3a5b-499b-be5f-97e49d2875e9.png) Reply file and link upload .torrent file /aria and /qbit please add this sir

Hey bro, I've added this feature, could you please check and let me know in case of any issues.

**Comment by rinrinx** [comment]
Thank you bro i Check
