### ISSUE TITLE
This link does not download and the bot freezes

### ISSUE THREAD

**Issue by rinrinx** [sachin0raon/Mirror2Gdrive#4]
![Screenshot_1](https://user-images.githubusercontent.com/91373907/218299943-3f9a0fbc-8626-4eb9-aad9-99dbf004b911.png)

magnet:?xt=urn:btih:2e766a9877ebfcddb003f3768c6ecaab8c3878bc&dn=Splice.2009.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-TURG.mkv&tr=http%3a%2f%2ftrack2.plux.me%3a2710%2f2969249a83b7b0414ba9614af471dbcb%2fannounce

**Comment by sachin0raon** [comment]
Fix was added so could you please retry and let me know in case of any issues.

**Comment by rinrinx** [comment]
Ok bro thanks i test bot
