### ISSUE TITLE
Status 

### ISSUE THREAD

**Issue by mohamedkaissi** [sachin0raon/Mirror2Gdrive#9]
Hi , thank you for this great project.
But the UI is a bit weird , can you make it easy like those mirror bots available, and support for index link , if it's possible

**Comment by mohamedkaissi** [comment]
Can you consider.

**Comment by mohamedkaissi** [comment]
I guess no need for those.
![Capture](https://user-images.githubusercontent.com/62901183/221872187-9e6ff98f-2421-4dde-92d6-fb88013c59b7.PNG)

**Comment by sachin0raon** [comment]
Due to some constraints, unfortunately, the upload status can't be combined with download status view.
